/**
 * Forge Beta Seed profile catalog.
 * Unified Discovery + Connections fixtures. Never written to Supabase.
 */

import {
  CHARACTER_SIGNAL_DEFINITIONS,
  type CharacterSignalId,
} from '@/lib/character-signals-mock';

export type SeedFactorSeverity =
  | 'informational'
  | 'worth_discussing'
  | 'potential_dealbreaker';

export type SeedAlignmentFactor = {
  id: string;
  title: string;
  severity: SeedFactorSeverity;
  summary: string;
  explanation: string;
  viewerAnswer?: string;
  partnerAnswer?: string;
  isPotentialDealbreaker?: boolean;
};

export type SeedProfile = {
  id: string;
  gender: 'woman' | 'man';
  firstName: string;
  lastName: string;
  age: number;
  locationCity: string;
  locationRegion: string;
  aboutPreview: string;
  moreAbout: string;
  career: string | null;
  education: string | null;
  thingsIEnjoy: string[];
  relationshipGoal: string | null;
  faithImportance: string | null;
  faithDescription?: string | null;
  children: string | null;
  hasChildren: string | null;
  openToPartnerWithChildren: string | null;
  smoking: string | null;
  drinking: string | null;
  relocation: string | null;
  serviceBackground: string | null;
  pets: string | null;
  alignmentLabel:
    | 'Strong Alignment'
    | 'Promising Alignment'
    | 'More to Discover'
    | 'Not Enough Information';
  sharedStrengths: string[];
  whySurfacedCopy?: string;
  importantFactors: SeedAlignmentFactor[];
  importantFactorsSummary: string | null;
  noFactorsCopy?: string;
  incompleteAssessmentCopy?: string;
  characterSignalIds: CharacterSignalId[];
  /** Whether this person appears as a mutual connection in Connections hub */
  isMutualConnection: boolean;
  /** Primary + lifestyle photo filenames under /seed-portraits/ */
  photoFiles: string[];
};

export type SeedPhoto = {
  id: string;
  storage_path: string;
  display_order: number;
  is_primary: boolean;
  public_url: string;
};

const SIGNAL_TITLE_BY_ID: Record<CharacterSignalId, string> = Object.fromEntries(
  CHARACTER_SIGNAL_DEFINITIONS.map((definition) => [definition.id, definition.title])
) as Record<CharacterSignalId, string>;

/** Map photo filenames to public seed-portrait photo objects. */
export function photos(photoFiles: string[]): SeedPhoto[] {
  return photoFiles.map((file, index) => ({
    id: file.replace(/\.[^.]+$/, ''),
    storage_path: `seed-portraits/${file}`,
    display_order: index,
    is_primary: index === 0,
    public_url: `/seed-portraits/${file}`,
  }));
}

/** Derive display titles from CharacterSignalId values. */
export function characterSignalTitles(ids: CharacterSignalId[]): string[] {
  return ids
    .map((id) => SIGNAL_TITLE_BY_ID[id])
    .filter((title): title is string => Boolean(title));
}

export const SEED_PROFILES: SeedProfile[] = [
  {
    id: "seed-amanda-cole",
    gender: "woman",
    firstName: "Amanda",
    lastName: "Cole",
    age: 40,
    locationCity: "Colorado Springs",
    locationRegion: "Colorado",
    aboutPreview: "Grounded and loyal, with a quiet sense of humor. Happiest when evenings feel calm, purposeful, and shared with people who show up.",
    moreAbout: "I work as a registered dental hygienist and have two kids who keep life full in the best way. Faith shapes how I treat people, and I want a partner who takes commitment seriously. I volunteer with a local food pantry most months, rarely drink, never smoke, and I am open to blending families if the relationship is built on respect.",
    career: "Registered dental hygienist",
    education: "associate",
    thingsIEnjoy: ["Dogs","Coffee shops","Trail walks","Cooking for friends"],
    relationshipGoal: "serious_relationship",
    faithImportance: "important",
    faithDescription: "Active in a local church community; faith guides daily decisions.",
    children: "open",
    hasChildren: "yes",
    openToPartnerWithChildren: "yes",
    smoking: "never",
    drinking: "occasionally",
    relocation: "possibly",
    serviceBackground: "community_service",
    pets: "dog",
    alignmentLabel: "Strong Alignment",
    sharedStrengths: [
          "Long-term relationship intentions align",
          "Faith carries similar importance",
          "Family and children preferences align",
          "Both are comfortable blending families",
          "Both value service and community",
          "Smoking preferences align"
    ],
    importantFactors: [],
    importantFactorsSummary: null,
    noFactorsCopy: "No major alignment concerns surfaced from the information currently available.",
    characterSignalIds: ["respectful_communicator","great_listener","clear_intentions","consistent_follow_through"] as CharacterSignalId[],
    isMutualConnection: true,
    photoFiles: ["amanda-cole-1.png","amanda-cole-2.png","amanda-cole-3.png"],
  },
  {
    id: "seed-sarah-bennett",
    gender: "woman",
    firstName: "Sarah",
    lastName: "Bennett",
    age: 36,
    locationCity: "Denver",
    locationRegion: "Colorado",
    aboutPreview: "Independent without being distant. I like live music, long weekend drives, and conversations that do not rush past the hard parts.",
    moreAbout: "I work in healthcare administration and do not have children yet. I am open to a partner who does, though I am still figuring out biological kids for myself. Spiritually curious more than highly religious. Non-smoker, social drinker, dog person, and pretty rooted near Denver for work and family.",
    career: "Healthcare administration",
    education: "bachelors",
    thingsIEnjoy: ["Weekend trips","Live music","Fitness","Dogs"],
    relationshipGoal: "serious_relationship",
    faithImportance: "somewhat_important",
    faithDescription: "Spiritual but not highly religious; open to shared values conversations.",
    children: "unsure",
    hasChildren: "no",
    openToPartnerWithChildren: "yes",
    smoking: "never",
    drinking: "socially",
    relocation: "not_open",
    serviceBackground: null,
    pets: "dog",
    alignmentLabel: "Promising Alignment",
    sharedStrengths: [
          "Both are looking for commitment",
          "Communication expectations appear compatible",
          "Both value family stability",
          "Smoking preferences align",
          "Both are open to established family life"
    ],
    importantFactors: [
      {
        id: "sarah-bennett-faith",
        title: "Faith",
        severity: "worth_discussing",
        summary: "Faith importance differs somewhat",
        explanation: "This may not be a problem, but it is worth discussing how faith or spirituality would show up in a relationship.",
        viewerAnswer: "Faith is an important relationship value",
        partnerAnswer: "Spiritual but not highly religious",
      },
      {
        id: "sarah-bennett-relocation",
        title: "Relocation",
        severity: "worth_discussing",
        summary: "Relocation preferences may differ",
        explanation: "Sarah prefers to remain near Denver. If a shared future becomes serious, location expectations are worth clarifying early.",
        viewerAnswer: "Open to relocating for the right relationship",
        partnerAnswer: "Prefers to remain near Denver",
      }
    ],
    importantFactorsSummary: "Faith and relocation deserve conversation",
    characterSignalIds: ["kind_conversation","great_listener","clear_intentions"] as CharacterSignalId[],
    isMutualConnection: false,
    photoFiles: ["sarah-bennett-1.png","sarah-bennett-2.png","sarah-bennett-3.png"],
  },
  {
    id: "seed-nicole-hayes",
    gender: "woman",
    firstName: "Nicole",
    lastName: "Hayes",
    age: 42,
    locationCity: "Castle Rock",
    locationRegion: "Colorado",
    aboutPreview: "Warm, ambitious, and selective about who gets close. I laugh easily and take honesty seriously.",
    moreAbout: "Corporate project manager with one teenage son. I do not want more biological children, but I am comfortable with a partner who already has kids. Faith matters to me personally. Non-smoker, rare drinker, and open to relocating within Colorado if the relationship is solid.",
    career: "Corporate project manager",
    education: "bachelors",
    thingsIEnjoy: ["Board games","Hiking","Fitness","Cooking"],
    relationshipGoal: "serious_relationship",
    faithImportance: "important",
    faithDescription: "Personally meaningful faith; prefers a partner who respects it.",
    children: "no",
    hasChildren: "yes",
    openToPartnerWithChildren: "yes",
    smoking: "never",
    drinking: "rarely",
    relocation: "possibly",
    serviceBackground: null,
    pets: "no_pets",
    alignmentLabel: "Promising Alignment",
    sharedStrengths: [
          "Commitment intentions align",
          "Blended-family openness aligns",
          "Similar priorities around stability",
          "Faith and values appear compatible",
          "Lifestyle preferences largely align"
    ],
    importantFactors: [
      {
        id: "nicole-hayes-children",
        title: "Children",
        severity: "worth_discussing",
        summary: "Future children preferences should be clarified",
        explanation: "Nicole does not want additional biological children. Clarifying long-term family plans helps both people move forward with care.",
        viewerAnswer: "Open to having or raising children within the relationship",
        partnerAnswer: "Does not want additional biological children",
      }
    ],
    importantFactorsSummary: "Future children preferences should be clarified",
    characterSignalIds: ["respectful_communicator","respectful_in_person","consistent_follow_through","great_listener"] as CharacterSignalId[],
    isMutualConnection: true,
    photoFiles: ["nicole-hayes-1.png","nicole-hayes-2.png","nicole-hayes-3.png"],
  },
  {
    id: "seed-rachel-ortiz",
    gender: "woman",
    firstName: "Rachel",
    lastName: "Ortiz",
    age: 38,
    locationCity: "Fort Collins",
    locationRegion: "Colorado",
    aboutPreview: "Curious, kind, and allergic to passive-aggressive silence. I would rather talk through friction than pretend it is not there.",
    moreAbout: "University program coordinator with no children and real uncertainty about parenting. Faith is not central to my week. Two cats, community arts nights, and a stubborn attachment to Fort Collins. Non-smoker and social drinker.",
    career: "University program coordinator",
    education: "graduate_professional",
    thingsIEnjoy: ["Community arts","Cats","Farmers markets","Reading"],
    relationshipGoal: "serious_relationship",
    faithImportance: "not_important",
    faithDescription: null,
    children: "unsure",
    hasChildren: "no",
    openToPartnerWithChildren: "unsure",
    smoking: "never",
    drinking: "socially",
    relocation: "not_open",
    serviceBackground: "community_service",
    pets: "cat",
    alignmentLabel: "More to Discover",
    sharedStrengths: [
          "Both want a meaningful relationship",
          "Communication priorities appear compatible",
          "Both value community involvement",
          "Geographic distance remains manageable"
    ],
    importantFactors: [
      {
        id: "rachel-ortiz-faith",
        title: "Faith",
        severity: "worth_discussing",
        summary: "Faith importance differs",
        explanation: "This difference may matter depending on how faith is practiced within a relationship.",
        viewerAnswer: "Faith is an important relationship value",
        partnerAnswer: "Faith is not central to daily life",
      },
      {
        id: "rachel-ortiz-parenting",
        title: "Children",
        severity: "informational",
        summary: "Parenting preferences are unclear",
        explanation: "Rachel is unsure about parenting. Incomplete or uncertain answers are not treated as negative — they invite conversation.",
      },
      {
        id: "rachel-ortiz-relocation",
        title: "Relocation",
        severity: "worth_discussing",
        summary: "Relocation preferences may differ",
        explanation: "Rachel feels strongly connected to Fort Collins. Shared home-base expectations are worth discussing if the relationship becomes serious.",
      }
    ],
    importantFactorsSummary: "Faith, parenting, and relocation need clarification",
    characterSignalIds: ["great_listener","respectful_communicator","handled_mismatch_respectfully"] as CharacterSignalId[],
    isMutualConnection: false,
    photoFiles: ["rachel-ortiz-1.png"],
  },
  {
    id: "seed-danielle-brooks",
    gender: "woman",
    firstName: "Danielle",
    lastName: "Brooks",
    age: 34,
    locationCity: "Parker",
    locationRegion: "Colorado",
    aboutPreview: "Steady energy, soft edges. I rebuild old furniture for fun and take Sunday mornings slowly on purpose.",
    moreAbout: "Occupational therapist who spent a few years in community health outreach. No kids yet and open to building a family. Faith is important — not performative, just woven into how I show care. Non-smoker, almost never drinks, and willing to relocate for the right partnership.",
    career: "Occupational therapist",
    education: "graduate_professional",
    thingsIEnjoy: ["Furniture refinishing","Sunday markets","Hiking","Podcasts"],
    relationshipGoal: "serious_relationship",
    faithImportance: "important",
    faithDescription: "Faith informs how she shows up for others; prefers aligned values.",
    children: "yes",
    hasChildren: "no",
    openToPartnerWithChildren: "yes",
    smoking: "never",
    drinking: "rarely",
    relocation: "open",
    serviceBackground: "healthcare",
    pets: "no_pets",
    alignmentLabel: "Strong Alignment",
    sharedStrengths: [
          "Both want a long-term committed relationship",
          "Faith is similarly important",
          "Family-building intentions align",
          "Service and caregiving values align",
          "Lifestyle habits appear compatible"
    ],
    importantFactors: [],
    importantFactorsSummary: null,
    noFactorsCopy: "No major alignment concerns surfaced from the information currently available.",
    characterSignalIds: ["genuine_and_present","kind_conversation","consistent_follow_through"] as CharacterSignalId[],
    isMutualConnection: false,
    photoFiles: ["danielle-brooks-1.png","danielle-brooks-2.png","danielle-brooks-3.png"],
  },
  {
    id: "seed-monica-ellis",
    gender: "woman",
    firstName: "Monica",
    lastName: "Ellis",
    age: 45,
    locationCity: "Littleton",
    locationRegion: "Colorado",
    aboutPreview: "Practical romantic. I plan road trips with spreadsheets and still leave room for spontaneous diners.",
    moreAbout: "High school counselor with adult children who are mostly out of the house. Open to a serious relationship without needing more kids of my own. Faith is somewhat important. Occasional wine with friends, never smoke, and I prefer staying along the Front Range.",
    career: "High school counselor",
    education: "graduate_professional",
    thingsIEnjoy: ["Road trips","Gardening","Book clubs","Cooking"],
    relationshipGoal: "serious_relationship",
    faithImportance: "somewhat_important",
    faithDescription: "Values faith communities but practices privately.",
    children: "no",
    hasChildren: "yes",
    openToPartnerWithChildren: "yes",
    smoking: "never",
    drinking: "occasionally",
    relocation: "not_open",
    serviceBackground: "education",
    pets: "dog",
    alignmentLabel: "Promising Alignment",
    sharedStrengths: [
          "Serious relationship goals align",
          "Both are comfortable with established family life",
          "Communication style appears thoughtful",
          "Smoking preferences align"
    ],
    importantFactors: [
      {
        id: "monica-ellis-timeline",
        title: "Marriage Timeline",
        severity: "informational",
        summary: "Marriage timeline may differ in pace",
        explanation: "Monica prefers a steady pace after past relationships. Timing expectations are worth naming early without treating either preference as wrong.",
        viewerAnswer: "Ready to move toward marriage within a few years",
        partnerAnswer: "Prefers a measured pace before discussing marriage",
      },
      {
        id: "monica-ellis-relocation",
        title: "Relocation",
        severity: "worth_discussing",
        summary: "Relocation preferences may differ",
        explanation: "Monica prefers remaining along the Front Range. Clarify whether a shared future needs geographic flexibility.",
      }
    ],
    importantFactorsSummary: "Marriage timeline and relocation deserve conversation",
    characterSignalIds: ["great_listener","respectful_communicator"] as CharacterSignalId[],
    isMutualConnection: false,
    photoFiles: ["monica-ellis-1.png"],
  },
  {
    id: "seed-kristin-walsh",
    gender: "woman",
    firstName: "Kristin",
    lastName: "Walsh",
    age: 39,
    locationCity: "Lakewood",
    locationRegion: "Colorado",
    aboutPreview: "Easygoing and thoughtful. Still filling in parts of my profile, but clear about wanting something meaningful.",
    moreAbout: "I work in insurance operations. Several structured preference fields are still unanswered, so Forge has limited relationship-preference information so far. I care about honest conversation and living near the mountains.",
    career: "Insurance operations",
    education: null,
    thingsIEnjoy: [],
    relationshipGoal: "serious_relationship",
    faithImportance: null,
    faithDescription: null,
    children: null,
    hasChildren: null,
    openToPartnerWithChildren: null,
    smoking: "never",
    drinking: null,
    relocation: null,
    serviceBackground: null,
    pets: null,
    alignmentLabel: "Not Enough Information",
    sharedStrengths: [
          "Interested in a serious relationship",
          "Values communication",
          "Lives within a reasonable distance"
    ],
    whySurfacedCopy: "Kristin’s stated relationship intentions and location may be relevant, but Forge needs more information before offering a responsible Relationship Alignment assessment.",
    importantFactors: [],
    importantFactorsSummary: null,
    noFactorsCopy: "Not enough information",
    incompleteAssessmentCopy: "Forge does not have enough information to offer a responsible Relationship Alignment assessment yet.",
    characterSignalIds: [] as CharacterSignalId[],
    isMutualConnection: false,
    photoFiles: ["kristin-walsh-1.png"],
  },
  {
    id: "seed-lauren-price",
    gender: "woman",
    firstName: "Lauren",
    lastName: "Price",
    age: 41,
    locationCity: "Boulder",
    locationRegion: "Colorado",
    aboutPreview: "Direct communicator who runs on tea, early mornings, and nonprofit deadlines. Looking for intentional partnership, not drama.",
    moreAbout: "Nonprofit director focused on housing stability work. No children and still deciding about parenting. Faith is not a decision-driver for me. Non-smoker; drinking answer still incomplete. Relocation unanswered for now.",
    career: "Nonprofit director",
    education: "graduate_professional",
    thingsIEnjoy: ["Reading","Trail running","Tea shops","Volunteer weekends"],
    relationshipGoal: "serious_relationship",
    faithImportance: "not_important",
    faithDescription: null,
    children: null,
    hasChildren: "no",
    openToPartnerWithChildren: null,
    smoking: "never",
    drinking: null,
    relocation: null,
    serviceBackground: "community_service",
    pets: null,
    alignmentLabel: "More to Discover",
    sharedStrengths: [
          "Both are seeking commitment",
          "Similar career stability",
          "Both value service",
          "Both prefer thoughtful communication"
    ],
    importantFactors: [
      {
        id: "lauren-price-faith",
        title: "Faith",
        severity: "worth_discussing",
        summary: "Faith importance differs",
        explanation: "This difference may matter depending on how faith is practiced within a relationship.",
        viewerAnswer: "Faith is an important relationship value",
        partnerAnswer: "Spiritual beliefs are personal but not central to relationship decisions",
      },
      {
        id: "lauren-price-drinking",
        title: "Drinking",
        severity: "informational",
        summary: "Drinking preferences need clarification",
        explanation: "Answers suggest incomplete social drinking preferences. Clarifying expectations early can prevent avoidable friction.",
      },
      {
        id: "lauren-price-relocation",
        title: "Relocation",
        severity: "informational",
        summary: "Relocation information is incomplete",
        explanation: "Forge does not yet have complete relocation answers. Missing information is not treated as negative.",
      },
      {
        id: "lauren-price-service",
        title: "Community Service",
        severity: "informational",
        summary: "Service rhythms may differ in intensity",
        explanation: "Lauren’s work and weekends often center on community service. Discuss how shared time and service commitments would balance.",
      }
    ],
    importantFactorsSummary: "Faith importance differs · more to clarify",
    characterSignalIds: ["great_listener","respectful_communicator","handled_mismatch_respectfully"] as CharacterSignalId[],
    isMutualConnection: true,
    photoFiles: ["lauren-price-1.png","lauren-price-2.png","lauren-price-3.png"],
  },
  {
    id: "seed-megan-torres",
    gender: "woman",
    firstName: "Megan",
    lastName: "Torres",
    age: 33,
    locationCity: "Aurora",
    locationRegion: "Colorado",
    aboutPreview: "Outdoorsy and family-minded. I pack coolers like it is a sport and text my siblings every day.",
    moreAbout: "Physical therapist who coaches youth soccer on weekends. No kids of my own yet; open to kids and to a partner who already has them. Faith is somewhat important. Dog named Bean. Prefer staying near Denver metro for now.",
    career: "Physical therapist",
    education: "graduate_professional",
    thingsIEnjoy: ["Camping","Youth soccer","Dogs","Weekend trips"],
    relationshipGoal: "serious_relationship",
    faithImportance: "somewhat_important",
    faithDescription: "Attends church occasionally; values shared moral grounding.",
    children: "open",
    hasChildren: "no",
    openToPartnerWithChildren: "yes",
    smoking: "never",
    drinking: "occasionally",
    relocation: "not_open",
    serviceBackground: "healthcare",
    pets: "dog",
    alignmentLabel: "Promising Alignment",
    sharedStrengths: [
          "Both want a serious relationship",
          "Family preferences generally align",
          "Both are non-smokers",
          "Similar stability and lifestyle priorities",
          "Both enjoy pets and outdoor activities"
    ],
    importantFactors: [
      {
        id: "megan-torres-relocation",
        title: "Relocation",
        severity: "worth_discussing",
        summary: "Relocation preferences differ",
        explanation: "This may not be a problem, but it is worth discussing if the relationship becomes serious.",
        viewerAnswer: "Open to relocating for the right relationship",
        partnerAnswer: "Prefers to remain near Denver metro",
      }
    ],
    importantFactorsSummary: "Relocation preferences differ",
    characterSignalIds: ["kind_conversation","clear_intentions","respectful_in_person","great_listener"] as CharacterSignalId[],
    isMutualConnection: false,
    photoFiles: ["megan-torres-1.png"],
  },
  {
    id: "seed-emily-chen",
    gender: "woman",
    firstName: "Emily",
    lastName: "Chen",
    age: 37,
    locationCity: "Boulder",
    locationRegion: "Colorado",
    aboutPreview: "Curious about a serious relationship and values clear communication. Several lifestyle answers are still incomplete.",
    moreAbout: "I am still completing parts of my Forge profile. I care about honest conversation and taking relationships seriously. Career and lifestyle details will come as I finish onboarding.",
    career: null,
    education: null,
    thingsIEnjoy: [],
    relationshipGoal: "serious_relationship",
    faithImportance: null,
    faithDescription: null,
    children: null,
    hasChildren: null,
    openToPartnerWithChildren: null,
    smoking: null,
    drinking: null,
    relocation: null,
    serviceBackground: null,
    pets: null,
    alignmentLabel: "Not Enough Information",
    sharedStrengths: [
          "Both appear interested in commitment",
          "Both value communication",
          "Similar geographic region"
    ],
    whySurfacedCopy: "Emily’s stated interest in a serious relationship and Front Range location may be relevant, but Forge needs more completed answers before offering a responsible Relationship Alignment assessment.",
    importantFactors: [],
    importantFactorsSummary: null,
    incompleteAssessmentCopy: "Forge does not have enough information to offer a responsible Relationship Alignment assessment yet.",
    characterSignalIds: [] as CharacterSignalId[],
    isMutualConnection: false,
    photoFiles: ["emily-chen-1.png"],
  },
  {
    id: "seed-jessica-rivera",
    gender: "woman",
    firstName: "Jessica",
    lastName: "Rivera",
    age: 38,
    locationCity: "Colorado Springs",
    locationRegion: "Colorado",
    aboutPreview: "Faith-centered and steady. I want a lasting partnership built on honesty, patience, and shared responsibility.",
    moreAbout: "Nurse practitioner with one child. Comfortable with a partner who has children. Faith is important and I serve at a community clinic once a month. Non-smoker, occasional drinker, open to relocating if both of us are all-in.",
    career: "Nurse practitioner",
    education: "graduate_professional",
    thingsIEnjoy: ["Camping","Coffee shops","Reading","Church community"],
    relationshipGoal: "serious_relationship",
    faithImportance: "important",
    faithDescription: "Faith is central to relationship and family decisions.",
    children: "open",
    hasChildren: "yes",
    openToPartnerWithChildren: "yes",
    smoking: "never",
    drinking: "occasionally",
    relocation: "open",
    serviceBackground: "healthcare",
    pets: "dog",
    alignmentLabel: "Strong Alignment",
    sharedStrengths: [
          "Both want a long-term committed relationship",
          "Faith is important",
          "Family and children preferences align",
          "Both are comfortable with a partner who already has children",
          "Both are non-smokers",
          "Both value service and community"
    ],
    importantFactors: [],
    importantFactorsSummary: null,
    noFactorsCopy: "No major alignment concerns surfaced from the information currently available.",
    characterSignalIds: ["respectful_communicator","great_listener","clear_intentions","consistent_follow_through"] as CharacterSignalId[],
    isMutualConnection: true,
    photoFiles: ["jessica-rivera-1.png","jessica-rivera-2.png","jessica-rivera-3.png"],
  },
  {
    id: "seed-hannah-brooks",
    gender: "woman",
    firstName: "Hannah",
    lastName: "Brooks",
    age: 29,
    locationCity: "Fort Collins",
    locationRegion: "Colorado",
    aboutPreview: "Optimistic realist. I keep a plant journal, coach my niece’s softball team, and text back when I say I will.",
    moreAbout: "Elementary school teacher. Want kids someday; do not have any yet. Faith is somewhat important. Smoke-free home is non-negotiable for me. Drink socially. Not eager to leave Colorado, but not closed off forever.",
    career: "Elementary school teacher",
    education: "bachelors",
    thingsIEnjoy: ["Softball","Houseplants","Baking","Board games"],
    relationshipGoal: "serious_relationship",
    faithImportance: "somewhat_important",
    faithDescription: null,
    children: "yes",
    hasChildren: "no",
    openToPartnerWithChildren: "yes",
    smoking: "never",
    drinking: "socially",
    relocation: "possibly",
    serviceBackground: "education",
    pets: "cat",
    alignmentLabel: "More to Discover",
    sharedStrengths: [
          "Both want a serious relationship",
          "Family-building interest appears shared",
          "Both value education and community"
    ],
    importantFactors: [
      {
        id: "hannah-brooks-smoking",
        title: "Smoking",
        severity: "potential_dealbreaker",
        summary: "Potential dealbreaker: Smoking preferences conflict",
        explanation: "Hannah requires a smoke-free home. Lifestyle conflicts around smoking can affect daily comfort and should be understood early.",
        viewerAnswer: "Occasional smoker",
        partnerAnswer: "Non-smoker; requires a smoke-free home",
        isPotentialDealbreaker: true,
      },
      {
        id: "hannah-brooks-faith",
        title: "Faith",
        severity: "informational",
        summary: "Faith importance is only partially aligned",
        explanation: "Differences in how central faith is may matter more once routines and holidays enter the picture.",
      },
      {
        id: "hannah-brooks-timeline",
        title: "Marriage Timeline",
        severity: "worth_discussing",
        summary: "Marriage timeline may need clarity",
        explanation: "Hannah is ready to build toward marriage but prefers not to rush. Aligning pace helps avoid mismatched expectations.",
      }
    ],
    importantFactorsSummary: "Potential dealbreaker: Smoking preferences conflict",
    characterSignalIds: ["clear_intentions","genuine_and_present"] as CharacterSignalId[],
    isMutualConnection: false,
    photoFiles: ["hannah-brooks-1.png"],
  },
  {
    id: "seed-olivia-grant",
    gender: "woman",
    firstName: "Olivia",
    lastName: "Grant",
    age: 44,
    locationCity: "Cheyenne",
    locationRegion: "Wyoming",
    aboutPreview: "Quiet confidence, big heart. I restore old trucks with my dad and host neighborhood potlucks in summer.",
    moreAbout: "Veterinarian with two kids splitting time between households. Open to a partner with children. Faith is important. Former Army reservist — structure still shapes my mornings. Rarely drink, never smoke, open to relocating for marriage.",
    career: "Veterinarian",
    education: "graduate_professional",
    thingsIEnjoy: ["Classic trucks","Potlucks","Dogs","Country music"],
    relationshipGoal: "serious_relationship",
    faithImportance: "important",
    faithDescription: "Faith and service background both shape her values.",
    children: "open",
    hasChildren: "yes",
    openToPartnerWithChildren: "yes",
    smoking: "never",
    drinking: "rarely",
    relocation: "open",
    serviceBackground: "military",
    pets: "dog",
    alignmentLabel: "Promising Alignment",
    sharedStrengths: [
          "Commitment intentions align",
          "Faith importance aligns",
          "Blended-family openness aligns",
          "Service background is valued",
          "Lifestyle habits largely compatible"
    ],
    importantFactors: [
      {
        id: "olivia-grant-military",
        title: "Military Service",
        severity: "informational",
        summary: "Military service background may shape daily rhythms",
        explanation: "Olivia’s reserve background influences structure and expectations. This is not a conflict by default — worth understanding how it shows up in home life.",
      }
    ],
    importantFactorsSummary: "Military service background may shape daily rhythms",
    characterSignalIds: ["consistent_follow_through","respectful_in_person","clear_intentions"] as CharacterSignalId[],
    isMutualConnection: false,
    photoFiles: ["olivia-grant-1.png"],
  },
  {
    id: "seed-sophia-martinez",
    gender: "woman",
    firstName: "Sophia",
    lastName: "Martinez",
    age: 31,
    locationCity: "Denver",
    locationRegion: "Colorado",
    aboutPreview: "Warm laugh, sharp mind. I teach dance on Tuesday nights and still call my grandma every Sunday.",
    moreAbout: "Marketing strategist who volunteers as a youth mentor. Want marriage and children. Faith is important. Smoke-free, drinks rarely, bilingual household energy, and open to relocating within the Mountain West.",
    career: "Marketing strategist",
    education: "bachelors",
    thingsIEnjoy: ["Dance","Family dinners","Hiking","Photography"],
    relationshipGoal: "serious_relationship",
    faithImportance: "important",
    faithDescription: "Faith and family traditions are central.",
    children: "yes",
    hasChildren: "no",
    openToPartnerWithChildren: "yes",
    smoking: "never",
    drinking: "rarely",
    relocation: "possibly",
    serviceBackground: "community_service",
    pets: "no_pets",
    alignmentLabel: "Strong Alignment",
    sharedStrengths: [
          "Long-term relationship intentions align",
          "Faith importance aligns",
          "Desire for children aligns",
          "Service and family values align",
          "Lifestyle preferences appear compatible"
    ],
    importantFactors: [],
    importantFactorsSummary: null,
    noFactorsCopy: "No major alignment concerns surfaced from the information currently available.",
    characterSignalIds: ["kind_conversation","genuine_and_present","clear_intentions","great_listener"] as CharacterSignalId[],
    isMutualConnection: false,
    photoFiles: ["sophia-martinez-1.png"],
  },
  {
    id: "seed-ashley-quinn",
    gender: "woman",
    firstName: "Ashley",
    lastName: "Quinn",
    age: 46,
    locationCity: "Pueblo",
    locationRegion: "Colorado",
    aboutPreview: "No-nonsense kindness. Twenty years in EMS taught me to stay calm when plans fall apart.",
    moreAbout: "Paramedic supervisor with grown stepkids from a previous marriage. Do not want more children. Faith is somewhat important. Occasional drinker, never smokes. Politics lean pragmatic and I prefer not to debate strangers online. Relocation is possible for the right person.",
    career: "Paramedic supervisor",
    education: "associate",
    thingsIEnjoy: ["Mountain drives","Strength training","True crime podcasts","Cooking"],
    relationshipGoal: "serious_relationship",
    faithImportance: "somewhat_important",
    faithDescription: null,
    children: "no",
    hasChildren: "yes",
    openToPartnerWithChildren: "yes",
    smoking: "never",
    drinking: "occasionally",
    relocation: "open",
    serviceBackground: "first_responder",
    pets: "dog",
    alignmentLabel: "More to Discover",
    sharedStrengths: [
          "Both want commitment",
          "Both value showing up under pressure",
          "Geographic fit is workable"
    ],
    importantFactors: [
      {
        id: "ashley-quinn-children",
        title: "Children",
        severity: "potential_dealbreaker",
        summary: "Potential dealbreaker: Children preferences differ",
        explanation: "These differences may affect long-term compatibility and should be understood before either person becomes deeply invested.",
        viewerAnswer: "Wants children within the relationship",
        partnerAnswer: "Does not want additional children",
        isPotentialDealbreaker: true,
      },
      {
        id: "ashley-quinn-first-responders",
        title: "First Responders",
        severity: "worth_discussing",
        summary: "First responder schedule may affect relationship rhythms",
        explanation: "Shift work and on-call realities can shape availability. Discussing expectations early helps both people plan with care.",
      },
      {
        id: "ashley-quinn-politics",
        title: "Politics",
        severity: "informational",
        summary: "Political style differs in intensity",
        explanation: "Ashley prefers low-conflict, pragmatic political conversation. Intensity of political engagement is worth a calm check-in.",
      }
    ],
    importantFactorsSummary: "Potential dealbreaker: Children preferences differ",
    characterSignalIds: ["respectful_communicator","handled_mismatch_respectfully"] as CharacterSignalId[],
    isMutualConnection: false,
    photoFiles: ["ashley-quinn-1.png"],
  },
  {
    id: "seed-brittany-hale",
    gender: "woman",
    firstName: "Brittany",
    lastName: "Hale",
    age: 35,
    locationCity: "Colorado Springs",
    locationRegion: "Colorado",
    aboutPreview: "Soft-spoken until something matters. Then I am clear. I love thrift stores, long walks, and people who keep their word.",
    moreAbout: "Librarian and weekend pottery student. Open to kids; do not have any yet. Faith is important. Prefer a partner who does not smoke. Drink rarely. Happy staying in Colorado Springs but willing to talk about nearby cities.",
    career: "Librarian",
    education: "graduate_professional",
    thingsIEnjoy: ["Pottery","Thrift stores","Walking trails","Reading"],
    relationshipGoal: "serious_relationship",
    faithImportance: "important",
    faithDescription: "Faith is a quiet daily practice and community anchor.",
    children: "open",
    hasChildren: "no",
    openToPartnerWithChildren: "yes",
    smoking: "never",
    drinking: "rarely",
    relocation: "possibly",
    serviceBackground: "education",
    pets: "cat",
    alignmentLabel: "Strong Alignment",
    sharedStrengths: [
          "Relationship goals align",
          "Faith importance aligns",
          "Openness around children aligns",
          "Communication preferences appear compatible",
          "Lifestyle habits largely align"
    ],
    importantFactors: [],
    importantFactorsSummary: null,
    noFactorsCopy: "No major alignment concerns surfaced from the information currently available.",
    characterSignalIds: ["genuine_and_present","great_listener","consistent_follow_through"] as CharacterSignalId[],
    isMutualConnection: false,
    photoFiles: ["brittany-hale-1.png"],
  },
  {
    id: "seed-courtney-diaz",
    gender: "woman",
    firstName: "Courtney",
    lastName: "Diaz",
    age: 32,
    locationCity: "Albuquerque",
    locationRegion: "New Mexico",
    aboutPreview: "Creative and grounded. I paint murals, coach my cousin’s debate team, and take dating seriously without making it heavy.",
    moreAbout: "Graphic designer with a side hustle in mural work. Unsure about children. Faith is not important to my daily life. Social drinker. Prefer staying in New Mexico for family reasons. Open to a partner with kids if the dynamic feels healthy.",
    career: "Graphic designer",
    education: "bachelors",
    thingsIEnjoy: ["Murals","Debate coaching","Farmers markets","Indie films"],
    relationshipGoal: "serious_relationship",
    faithImportance: "not_important",
    faithDescription: null,
    children: "unsure",
    hasChildren: "no",
    openToPartnerWithChildren: "yes",
    smoking: "never",
    drinking: "socially",
    relocation: "not_open",
    serviceBackground: "community_service",
    pets: "dog",
    alignmentLabel: "More to Discover",
    sharedStrengths: [
          "Both want a meaningful committed relationship",
          "Both value creative expression and community",
          "Communication appears respectful"
    ],
    importantFactors: [
      {
        id: "courtney-diaz-faith",
        title: "Faith",
        severity: "worth_discussing",
        summary: "Faith importance differs",
        explanation: "Courtney does not center faith in daily life. How that intersects with a faith-important partner needs an honest conversation.",
        viewerAnswer: "Faith is an important relationship value",
        partnerAnswer: "Faith is not important to daily life",
      },
      {
        id: "courtney-diaz-relocation",
        title: "Relocation",
        severity: "worth_discussing",
        summary: "Relocation preferences may conflict",
        explanation: "Courtney prefers remaining in New Mexico for family. A shared future may require geographic compromise discussions.",
      },
      {
        id: "courtney-diaz-children",
        title: "Children",
        severity: "informational",
        summary: "Children intentions are still forming",
        explanation: "Uncertainty around children is not treated as negative. Conversation helps clarify direction over time.",
      },
      {
        id: "courtney-diaz-lifestyle",
        title: "Lifestyle",
        severity: "informational",
        summary: "Creative work schedule may differ from a 9-to-5 rhythm",
        explanation: "Project-based creative work can create irregular evenings. Discussing routines helps set expectations.",
      }
    ],
    importantFactorsSummary: "Faith, relocation, and children need clarification",
    characterSignalIds: ["kind_conversation","clear_intentions"] as CharacterSignalId[],
    isMutualConnection: true,
    photoFiles: ["courtney-diaz-1.png","courtney-diaz-2.png","courtney-diaz-3.png"],
  },
  {
    id: "seed-natalie-kim",
    gender: "woman",
    firstName: "Natalie",
    lastName: "Kim",
    age: 39,
    locationCity: "Pueblo",
    locationRegion: "Colorado",
    aboutPreview: "Clear about intentions and allergic to mixed signals. Prefer honest early conversations over months of guessing.",
    moreAbout: "Operations lead at a regional logistics company. Do not want children and do not want a parenting role. Occasional smoker — working on quitting. Drink socially. Open to relocating. Faith answers left blank for now.",
    career: "Operations lead",
    education: "bachelors",
    thingsIEnjoy: ["Coffee shops","Board games","Cycling","Cooking shows"],
    relationshipGoal: "serious_relationship",
    faithImportance: null,
    faithDescription: null,
    children: "no",
    hasChildren: "no",
    openToPartnerWithChildren: "no",
    smoking: "occasionally",
    drinking: "occasionally",
    relocation: "open",
    serviceBackground: null,
    pets: null,
    alignmentLabel: "More to Discover",
    sharedStrengths: [
          "Both value respectful communication",
          "Both prefer commitment",
          "Geographic distance is manageable"
    ],
    importantFactors: [
      {
        id: "natalie-kim-children",
        title: "Children",
        severity: "potential_dealbreaker",
        summary: "Potential dealbreaker: Children preferences differ",
        explanation: "These differences may affect long-term compatibility and should be understood before either person becomes deeply invested.",
        viewerAnswer: "Open to having or raising children within the relationship",
        partnerAnswer: "Does not want children and does not want a parenting role",
        isPotentialDealbreaker: true,
      },
      {
        id: "natalie-kim-smoking",
        title: "Smoking",
        severity: "worth_discussing",
        summary: "Smoking preferences conflict",
        explanation: "Lifestyle preferences around smoking can affect daily comfort and long-term fit. This is an important difference worth discussing before moving forward.",
        viewerAnswer: "Non-smoker and prefers a non-smoking partner",
        partnerAnswer: "Occasional smoker",
      }
    ],
    importantFactorsSummary: "Potential dealbreaker: Children preferences differ",
    characterSignalIds: ["respectful_communicator","clear_intentions"] as CharacterSignalId[],
    isMutualConnection: false,
    photoFiles: ["natalie-kim-1.png"],
  },
  {
    id: "seed-victoria-lane",
    gender: "woman",
    firstName: "Victoria",
    lastName: "Lane",
    age: 43,
    locationCity: "Castle Rock",
    locationRegion: "Colorado",
    aboutPreview: "Elegant without being precious. I host dinner parties that end in dishwashing and storytelling, not performance.",
    moreAbout: "Estate attorney with one college-age daughter. Open to a serious relationship; not looking for more children. Faith is important. Rare drinker, never smokes. Prefer staying in Colorado but would discuss a partner’s career move thoughtfully.",
    career: "Estate attorney",
    education: "graduate_professional",
    thingsIEnjoy: ["Dinner parties","Classical music","Hiking","Travel"],
    relationshipGoal: "serious_relationship",
    faithImportance: "important",
    faithDescription: "Faith informs ethics and family priorities.",
    children: "no",
    hasChildren: "yes",
    openToPartnerWithChildren: "yes",
    smoking: "never",
    drinking: "rarely",
    relocation: "possibly",
    serviceBackground: null,
    pets: "cat",
    alignmentLabel: "Promising Alignment",
    sharedStrengths: [
          "Commitment intentions align",
          "Faith importance aligns",
          "Comfort with established family life aligns",
          "Lifestyle habits appear compatible"
    ],
    importantFactors: [
      {
        id: "victoria-lane-family",
        title: "Family Priorities",
        severity: "worth_discussing",
        summary: "Family priorities differ in emphasis",
        explanation: "Victoria’s adult child remains a central priority. Clarifying how blended family time is shared helps both people feel respected.",
        viewerAnswer: "Wants a partner-centered household rhythm",
        partnerAnswer: "Adult child remains a standing weekly priority",
      },
      {
        id: "victoria-lane-timeline",
        title: "Marriage Timeline",
        severity: "informational",
        summary: "Marriage timeline may be slower by design",
        explanation: "After a long marriage ended, Victoria prefers intentional pacing. This is informational, not a mismatch by default.",
      }
    ],
    importantFactorsSummary: "Family priorities and marriage timeline deserve conversation",
    characterSignalIds: ["respectful_communicator","great_listener","respectful_in_person"] as CharacterSignalId[],
    isMutualConnection: false,
    photoFiles: ["victoria-lane-1.png"],
  },
  {
    id: "seed-rebecca-frost",
    gender: "woman",
    firstName: "Rebecca",
    lastName: "Frost",
    age: 28,
    locationCity: "Denver",
    locationRegion: "Colorado",
    aboutPreview: "New to Forge and still completing my profile. Looking for something real when the answers are ready.",
    moreAbout: "Software support specialist who just moved back to Denver. Profile preferences around faith, children, and lifestyle are incomplete. I know I want a serious relationship and clear communication.",
    career: "Software support specialist",
    education: "associate",
    thingsIEnjoy: ["Climbing gym","Coffee"],
    relationshipGoal: "serious_relationship",
    faithImportance: null,
    faithDescription: null,
    children: null,
    hasChildren: null,
    openToPartnerWithChildren: null,
    smoking: null,
    drinking: null,
    relocation: null,
    serviceBackground: null,
    pets: null,
    alignmentLabel: "Not Enough Information",
    sharedStrengths: [
          "Interested in a serious relationship",
          "Local to the Front Range",
          "Values clear communication"
    ],
    whySurfacedCopy: "Rebecca’s relationship goal and Denver location may be relevant, but Forge needs more completed preference answers before offering a responsible Relationship Alignment assessment.",
    importantFactors: [],
    importantFactorsSummary: null,
    incompleteAssessmentCopy: "Forge does not have enough information to offer a responsible Relationship Alignment assessment yet.",
    characterSignalIds: [] as CharacterSignalId[],
    isMutualConnection: false,
    photoFiles: ["rebecca-frost-1.png"],
  },
  {
    id: "seed-michael-turner",
    gender: "man",
    firstName: "Michael",
    lastName: "Turner",
    age: 41,
    locationCity: "Colorado Springs",
    locationRegion: "Colorado",
    aboutPreview: "Steady presence. I coach baseball, fix things around the house, and take faith and family seriously without making a speech about it.",
    moreAbout: "Mechanical engineer and former Air Force maintainer. Two kids. Open to blending families. Faith is important. Non-smoker, occasional drinker, and willing to relocate within Colorado for the right marriage.",
    career: "Mechanical engineer",
    education: "bachelors",
    thingsIEnjoy: ["Baseball coaching","Home projects","Camping","Coffee"],
    relationshipGoal: "serious_relationship",
    faithImportance: "important",
    faithDescription: "Faith and family are central priorities.",
    children: "open",
    hasChildren: "yes",
    openToPartnerWithChildren: "yes",
    smoking: "never",
    drinking: "occasionally",
    relocation: "possibly",
    serviceBackground: "military",
    pets: "dog",
    alignmentLabel: "Strong Alignment",
    sharedStrengths: [
          "Long-term relationship intentions align",
          "Faith importance aligns",
          "Family and blended-family openness align",
          "Service background is mutually valued",
          "Lifestyle habits appear compatible"
    ],
    importantFactors: [],
    importantFactorsSummary: null,
    noFactorsCopy: "No major alignment concerns surfaced from the information currently available.",
    characterSignalIds: ["respectful_communicator","consistent_follow_through","clear_intentions","respectful_in_person"] as CharacterSignalId[],
    isMutualConnection: true,
    photoFiles: ["michael-turner-1.png","michael-turner-2.png","michael-turner-3.png"],
  },
  {
    id: "seed-david-nguyen",
    gender: "man",
    firstName: "David",
    lastName: "Nguyen",
    age: 36,
    locationCity: "Denver",
    locationRegion: "Colorado",
    aboutPreview: "Curious and calm. I cook Vietnamese food for friends, bike to work when weather allows, and prefer deep talks over small talk marathons.",
    moreAbout: "Product manager in health tech. No kids; open to them and to a partner with kids. Faith is somewhat important. Non-smoker, social drinker. Prefer staying near Denver for career and family.",
    career: "Product manager",
    education: "bachelors",
    thingsIEnjoy: ["Cooking","Cycling","Board games","Weekend markets"],
    relationshipGoal: "serious_relationship",
    faithImportance: "somewhat_important",
    faithDescription: null,
    children: "open",
    hasChildren: "no",
    openToPartnerWithChildren: "yes",
    smoking: "never",
    drinking: "socially",
    relocation: "not_open",
    serviceBackground: null,
    pets: "no_pets",
    alignmentLabel: "Promising Alignment",
    sharedStrengths: [
          "Both want a serious relationship",
          "Family openness generally aligns",
          "Communication style appears thoughtful",
          "Smoking preferences align"
    ],
    importantFactors: [
      {
        id: "david-nguyen-faith",
        title: "Faith",
        severity: "worth_discussing",
        summary: "Faith importance differs somewhat",
        explanation: "David treats faith as meaningful but not central. Discuss how shared values would look in practice.",
        viewerAnswer: "Faith is an important relationship value",
        partnerAnswer: "Faith is somewhat important",
      },
      {
        id: "david-nguyen-relocation",
        title: "Relocation",
        severity: "worth_discussing",
        summary: "Relocation preferences may differ",
        explanation: "David prefers remaining near Denver. Clarify geographic expectations early if the relationship deepens.",
      }
    ],
    importantFactorsSummary: "Faith and relocation deserve conversation",
    characterSignalIds: ["great_listener","kind_conversation","genuine_and_present"] as CharacterSignalId[],
    isMutualConnection: false,
    photoFiles: ["david-nguyen-1.png"],
  },
  {
    id: "seed-james-carter",
    gender: "man",
    firstName: "James",
    lastName: "Carter",
    age: 48,
    locationCity: "Pueblo",
    locationRegion: "Colorado",
    aboutPreview: "Dry humor, dependable hands. I restore motorcycles and show up for the people I claim.",
    moreAbout: "Union electrician with adult children. Do not want more kids. Faith is important. Occasional beer, never smokes. Politics are traditional and I talk about them carefully. Open to relocating within Colorado.",
    career: "Union electrician",
    education: "trade",
    thingsIEnjoy: ["Motorcycles","Fishing","BBQ","Classic rock"],
    relationshipGoal: "serious_relationship",
    faithImportance: "important",
    faithDescription: "Faith informs marriage and integrity expectations.",
    children: "no",
    hasChildren: "yes",
    openToPartnerWithChildren: "yes",
    smoking: "never",
    drinking: "occasionally",
    relocation: "possibly",
    serviceBackground: null,
    pets: "dog",
    alignmentLabel: "More to Discover",
    sharedStrengths: [
          "Both want lasting commitment",
          "Faith importance aligns",
          "Lifestyle habits largely compatible"
    ],
    importantFactors: [
      {
        id: "james-carter-children",
        title: "Children",
        severity: "worth_discussing",
        summary: "Future children preferences should be clarified",
        explanation: "James does not want more children. If a partner wants kids, this needs early clarity.",
        viewerAnswer: "Open to having children",
        partnerAnswer: "Does not want additional children",
      },
      {
        id: "james-carter-politics",
        title: "Politics",
        severity: "informational",
        summary: "Political outlook may differ in emphasis",
        explanation: "James holds traditional political views and prefers measured conversation. Intensity and topics are worth a respectful check-in.",
      },
      {
        id: "james-carter-lifestyle",
        title: "Lifestyle",
        severity: "informational",
        summary: "Trade-work schedule and hobbies shape weekends",
        explanation: "Project weekends and shop time matter to James. Shared leisure expectations are worth naming.",
      }
    ],
    importantFactorsSummary: "Children preferences and lifestyle deserve conversation",
    characterSignalIds: ["clear_intentions","respectful_communicator","handled_mismatch_respectfully"] as CharacterSignalId[],
    isMutualConnection: false,
    photoFiles: ["james-carter-1.png"],
  },
  {
    id: "seed-christopher-bell",
    gender: "man",
    firstName: "Christopher",
    lastName: "Bell",
    age: 37,
    locationCity: "Fort Collins",
    locationRegion: "Colorado",
    aboutPreview: "Patient listener. I teach Sunday school, trail run before work, and want a marriage that feels like a team.",
    moreAbout: "Civil engineer with no children yet and a clear desire for family. Faith is important. Non-smoker, rarely drinks. Community service through Habitat builds. Open to relocating for the right partnership.",
    career: "Civil engineer",
    education: "bachelors",
    thingsIEnjoy: ["Trail running","Sunday school","Habitat builds","Cooking"],
    relationshipGoal: "serious_relationship",
    faithImportance: "important",
    faithDescription: "Active faith community involvement.",
    children: "yes",
    hasChildren: "no",
    openToPartnerWithChildren: "yes",
    smoking: "never",
    drinking: "rarely",
    relocation: "open",
    serviceBackground: "community_service",
    pets: "dog",
    alignmentLabel: "Strong Alignment",
    sharedStrengths: [
          "Relationship goals align",
          "Faith importance aligns",
          "Desire for children aligns",
          "Service values align",
          "Lifestyle habits appear compatible"
    ],
    importantFactors: [],
    importantFactorsSummary: null,
    noFactorsCopy: "No major alignment concerns surfaced from the information currently available.",
    characterSignalIds: ["great_listener","consistent_follow_through","clear_intentions","genuine_and_present"] as CharacterSignalId[],
    isMutualConnection: false,
    photoFiles: ["christopher-bell-1.png"],
  },
  {
    id: "seed-matthew-ruiz",
    gender: "man",
    firstName: "Matthew",
    lastName: "Ruiz",
    age: 34,
    locationCity: "Aurora",
    locationRegion: "Colorado",
    aboutPreview: "Protective without being controlling. I cook for my nieces, lift early, and try to leave people better than I found them.",
    moreAbout: "Police officer with a side interest in coaching youth boxing. No kids; open to kids and partners with kids. Faith is somewhat important. Non-smoker, rare drinker. Prefer staying in Colorado metro for work.",
    career: "Police officer",
    education: "bachelors",
    thingsIEnjoy: ["Weightlifting","Youth boxing","Cooking","Movies"],
    relationshipGoal: "serious_relationship",
    faithImportance: "somewhat_important",
    faithDescription: null,
    children: "open",
    hasChildren: "no",
    openToPartnerWithChildren: "yes",
    smoking: "never",
    drinking: "rarely",
    relocation: "not_open",
    serviceBackground: "law_enforcement",
    pets: "dog",
    alignmentLabel: "Promising Alignment",
    sharedStrengths: [
          "Serious relationship intentions align",
          "Family openness aligns",
          "Service vocation is respected",
          "Lifestyle habits largely compatible"
    ],
    importantFactors: [
      {
        id: "matthew-ruiz-law",
        title: "Law Enforcement",
        severity: "worth_discussing",
        summary: "Law enforcement schedule and stress deserve conversation",
        explanation: "Shift work and occupational stress can affect relationship rhythms. Understanding expectations early supports a healthier partnership.",
        viewerAnswer: "Prefers predictable evening availability",
        partnerAnswer: "Rotating shifts and on-call realities",
      },
      {
        id: "matthew-ruiz-relocation",
        title: "Relocation",
        severity: "informational",
        summary: "Relocation preferences may differ",
        explanation: "Matthew prefers remaining near his department. Geographic flexibility may be limited in the near term.",
      }
    ],
    importantFactorsSummary: "Law enforcement schedule deserves conversation",
    characterSignalIds: ["respectful_in_person","consistent_follow_through","kind_conversation"] as CharacterSignalId[],
    isMutualConnection: true,
    photoFiles: ["matthew-ruiz-1.png","matthew-ruiz-2.png","matthew-ruiz-3.png"],
  },
  {
    id: "seed-andrew-scott",
    gender: "man",
    firstName: "Andrew",
    lastName: "Scott",
    age: 40,
    locationCity: "Lakewood",
    locationRegion: "Colorado",
    aboutPreview: "Still finishing my Forge answers. I know I want commitment and honest communication.",
    moreAbout: "IT systems analyst recently back on the dating scene after a long pause. Several preference fields remain incomplete, so Forge cannot yet offer a full alignment read.",
    career: "IT systems analyst",
    education: null,
    thingsIEnjoy: [],
    relationshipGoal: "serious_relationship",
    faithImportance: null,
    faithDescription: null,
    children: null,
    hasChildren: null,
    openToPartnerWithChildren: null,
    smoking: null,
    drinking: null,
    relocation: null,
    serviceBackground: null,
    pets: null,
    alignmentLabel: "Not Enough Information",
    sharedStrengths: [
          "Interested in a serious relationship",
          "Local to the Front Range",
          "Values honest communication"
    ],
    whySurfacedCopy: "Andrew’s stated relationship intentions and location may be relevant, but Forge needs more information before offering a responsible Relationship Alignment assessment.",
    importantFactors: [],
    importantFactorsSummary: null,
    incompleteAssessmentCopy: "Forge does not have enough information to offer a responsible Relationship Alignment assessment yet.",
    characterSignalIds: [] as CharacterSignalId[],
    isMutualConnection: false,
    photoFiles: ["andrew-scott-1.png"],
  },
  {
    id: "seed-joshua-klein",
    gender: "man",
    firstName: "Joshua",
    lastName: "Klein",
    age: 30,
    locationCity: "Boulder",
    locationRegion: "Colorado",
    aboutPreview: "Thoughtful and a little nerdy. I lead a synagogue young-adults group and climb when the weather cooperates.",
    moreAbout: "Data scientist who cares about building a Jewish household someday. Want kids. Faith is important in a specifically Jewish way. Non-smoker, drinks socially. Prefer staying near Boulder or Denver.",
    career: "Data scientist",
    education: "graduate_professional",
    thingsIEnjoy: ["Climbing","Board games","Cooking","Synagogue community"],
    relationshipGoal: "serious_relationship",
    faithImportance: "important",
    faithDescription: "Jewish faith and tradition are central to family life.",
    children: "yes",
    hasChildren: "no",
    openToPartnerWithChildren: "yes",
    smoking: "never",
    drinking: "socially",
    relocation: "not_open",
    serviceBackground: "community_service",
    pets: "no_pets",
    alignmentLabel: "More to Discover",
    sharedStrengths: [
          "Both want a serious relationship",
          "Desire for children appears shared",
          "Community involvement is valued"
    ],
    importantFactors: [
      {
        id: "joshua-klein-faith",
        title: "Faith",
        severity: "worth_discussing",
        summary: "Faith tradition and practice may differ",
        explanation: "Joshua wants a household shaped by Jewish tradition. How faith is practiced together needs an early, respectful conversation.",
        viewerAnswer: "Christian faith is central",
        partnerAnswer: "Jewish faith and tradition are central",
      },
      {
        id: "joshua-klein-relocation",
        title: "Relocation",
        severity: "worth_discussing",
        summary: "Relocation preferences may differ",
        explanation: "Joshua prefers remaining near Boulder or Denver for community reasons.",
      },
      {
        id: "joshua-klein-drinking",
        title: "Drinking",
        severity: "informational",
        summary: "Social drinking preferences may differ",
        explanation: "Differences in social drinking are often workable — still worth naming expectations.",
      }
    ],
    importantFactorsSummary: "Faith tradition and relocation need clarification",
    characterSignalIds: ["clear_intentions","great_listener","genuine_and_present"] as CharacterSignalId[],
    isMutualConnection: false,
    photoFiles: ["joshua-klein-1.png"],
  },
  {
    id: "seed-ryan-cooper",
    gender: "man",
    firstName: "Ryan",
    lastName: "Cooper",
    age: 38,
    locationCity: "Parker",
    locationRegion: "Colorado",
    aboutPreview: "Loyal and lighthearted. I burn pancakes on purpose for my kids’ amusement and still make it to church on time.",
    moreAbout: "Firefighter/paramedic with two children. Open to blending families. Faith is important. Non-smoker, rare drinker. Community service is part of the job and the weekends. Open to relocating if both households agree.",
    career: "Firefighter / paramedic",
    education: "associate",
    thingsIEnjoy: ["Kids sports","Camping","Church community","Grilling"],
    relationshipGoal: "serious_relationship",
    faithImportance: "important",
    faithDescription: "Faith and first-responder service shape his values.",
    children: "open",
    hasChildren: "yes",
    openToPartnerWithChildren: "yes",
    smoking: "never",
    drinking: "rarely",
    relocation: "open",
    serviceBackground: "first_responder",
    pets: "dog",
    alignmentLabel: "Strong Alignment",
    sharedStrengths: [
          "Long-term relationship intentions align",
          "Faith importance aligns",
          "Family and blended-family openness align",
          "Service values align",
          "Lifestyle habits appear compatible"
    ],
    importantFactors: [],
    importantFactorsSummary: null,
    noFactorsCopy: "No major alignment concerns surfaced from the information currently available.",
    characterSignalIds: ["respectful_communicator","consistent_follow_through","kind_conversation","respectful_in_person"] as CharacterSignalId[],
    isMutualConnection: true,
    photoFiles: ["ryan-cooper-1.png","ryan-cooper-2.png","ryan-cooper-3.png"],
  },
  {
    id: "seed-brandon-miles",
    gender: "man",
    firstName: "Brandon",
    lastName: "Miles",
    age: 42,
    locationCity: "Littleton",
    locationRegion: "Colorado",
    aboutPreview: "Low-key and reliable. I restore vinyl, coach middle-school basketball, and prefer relationships that grow without theatrics.",
    moreAbout: "High school athletic director. Has one teenager. Open to a partner with kids; not seeking more biological children. Faith is somewhat important. Non-smoker, occasional drinker. Prefer remaining in the Denver south metro.",
    career: "High school athletic director",
    education: "bachelors",
    thingsIEnjoy: ["Basketball coaching","Vinyl records","Hiking","Coffee"],
    relationshipGoal: "serious_relationship",
    faithImportance: "somewhat_important",
    faithDescription: null,
    children: "no",
    hasChildren: "yes",
    openToPartnerWithChildren: "yes",
    smoking: "never",
    drinking: "occasionally",
    relocation: "not_open",
    serviceBackground: "education",
    pets: "dog",
    alignmentLabel: "Promising Alignment",
    sharedStrengths: [
          "Commitment intentions align",
          "Blended-family openness aligns",
          "Education and community values align",
          "Lifestyle habits largely compatible"
    ],
    importantFactors: [
      {
        id: "brandon-miles-children",
        title: "Children",
        severity: "worth_discussing",
        summary: "Future children preferences should be clarified",
        explanation: "Brandon does not want additional biological children. Clarify long-term family plans with care.",
        viewerAnswer: "Open to having children",
        partnerAnswer: "Does not want additional biological children",
      }
    ],
    importantFactorsSummary: "Future children preferences should be clarified",
    characterSignalIds: ["great_listener","clear_intentions"] as CharacterSignalId[],
    isMutualConnection: false,
    photoFiles: ["brandon-miles-1.png"],
  },
  {
    id: "seed-tyler-shaw",
    gender: "man",
    firstName: "Tyler",
    lastName: "Shaw",
    age: 29,
    locationCity: "Colorado Springs",
    locationRegion: "Colorado",
    aboutPreview: "Ambitious without being flashy. I save aggressively, climb on Saturdays, and want a partner who talks about money without flinching.",
    moreAbout: "Commercial real estate analyst. Unsure about kids. Faith is not important. Social drinker. Occasional cigar at celebrations — flagged under smoking. Open to relocating for career or marriage.",
    career: "Commercial real estate analyst",
    education: "bachelors",
    thingsIEnjoy: ["Climbing","Personal finance podcasts","Concerts","Travel"],
    relationshipGoal: "serious_relationship",
    faithImportance: "not_important",
    faithDescription: null,
    children: "unsure",
    hasChildren: "no",
    openToPartnerWithChildren: "unsure",
    smoking: "occasionally",
    drinking: "socially",
    relocation: "open",
    serviceBackground: null,
    pets: null,
    alignmentLabel: "More to Discover",
    sharedStrengths: [
          "Both want a serious relationship",
          "Both value direct communication",
          "Geographic flexibility may help"
    ],
    importantFactors: [
      {
        id: "tyler-shaw-faith",
        title: "Faith",
        severity: "worth_discussing",
        summary: "Faith importance differs",
        explanation: "Tyler does not treat faith as important. This may matter depending on how faith is practiced in a relationship.",
        viewerAnswer: "Faith is an important relationship value",
        partnerAnswer: "Faith is not important",
      },
      {
        id: "tyler-shaw-smoking",
        title: "Smoking",
        severity: "worth_discussing",
        summary: "Smoking preferences may conflict",
        explanation: "Occasional cigars may conflict with a smoke-free preference. Worth discussing boundaries early.",
      },
      {
        id: "tyler-shaw-children",
        title: "Children",
        severity: "informational",
        summary: "Children intentions are still forming",
        explanation: "Uncertainty around children invites conversation rather than a negative assumption.",
      },
      {
        id: "tyler-shaw-lifestyle",
        title: "Lifestyle",
        severity: "informational",
        summary: "Career intensity and travel may affect availability",
        explanation: "Deal cycles and travel can shape weeknight availability. Expectations are worth naming.",
      }
    ],
    importantFactorsSummary: "Faith and smoking deserve conversation",
    characterSignalIds: ["clear_intentions","handled_mismatch_respectfully"] as CharacterSignalId[],
    isMutualConnection: false,
    photoFiles: ["tyler-shaw-1.png"],
  },
  {
    id: "seed-kevin-morgan",
    gender: "man",
    firstName: "Kevin",
    lastName: "Morgan",
    age: 45,
    locationCity: "Omaha",
    locationRegion: "Nebraska",
    aboutPreview: "Warm Midwestern manners, Colorado roots. I visit family in Springs monthly and want a partner who understands long drives for people you love.",
    moreAbout: "Hospital administrator with one adult child. Open to a serious relationship without more kids. Faith is important. Non-smoker, rare drinker. Willing to relocate back to Colorado for marriage.",
    career: "Hospital administrator",
    education: "graduate_professional",
    thingsIEnjoy: ["Golf","Family visits","Jazz","Cooking"],
    relationshipGoal: "serious_relationship",
    faithImportance: "important",
    faithDescription: "Faith informs leadership and family life.",
    children: "no",
    hasChildren: "yes",
    openToPartnerWithChildren: "yes",
    smoking: "never",
    drinking: "rarely",
    relocation: "open",
    serviceBackground: "healthcare",
    pets: "no_pets",
    alignmentLabel: "Promising Alignment",
    sharedStrengths: [
          "Commitment intentions align",
          "Faith importance aligns",
          "Healthcare and service values align",
          "Lifestyle habits appear compatible"
    ],
    importantFactors: [
      {
        id: "kevin-morgan-relocation",
        title: "Relocation",
        severity: "worth_discussing",
        summary: "Relocation is likely required for proximity",
        explanation: "Kevin currently lives in Omaha and is open to returning to Colorado. Timing and logistics of relocation deserve early conversation.",
        viewerAnswer: "Lives in Colorado",
        partnerAnswer: "Lives in Omaha; open to relocating to Colorado",
      },
      {
        id: "kevin-morgan-family",
        title: "Family Priorities",
        severity: "informational",
        summary: "Adult child remains an important priority",
        explanation: "Kevin maintains a close relationship with an adult child. Shared family rhythms are worth discussing.",
      }
    ],
    importantFactorsSummary: "Relocation logistics deserve conversation",
    characterSignalIds: ["respectful_communicator","great_listener","consistent_follow_through"] as CharacterSignalId[],
    isMutualConnection: false,
    photoFiles: ["kevin-morgan-1.png"],
  },
  {
    id: "seed-justin-reed",
    gender: "man",
    firstName: "Justin",
    lastName: "Reed",
    age: 33,
    locationCity: "Denver",
    locationRegion: "Colorado",
    aboutPreview: "Earnest and funny. I lead a small group at church, brew coffee like it is a craft, and want a marriage built on friendship first.",
    moreAbout: "Software engineer volunteering with a youth mentoring nonprofit. Want kids. Faith is important. Non-smoker, rarely drinks. Open to relocating within the Mountain West.",
    career: "Software engineer",
    education: "bachelors",
    thingsIEnjoy: ["Coffee brewing","Youth mentoring","Skiing","Board games"],
    relationshipGoal: "serious_relationship",
    faithImportance: "important",
    faithDescription: "Active church involvement; faith shapes relationship goals.",
    children: "yes",
    hasChildren: "no",
    openToPartnerWithChildren: "yes",
    smoking: "never",
    drinking: "rarely",
    relocation: "possibly",
    serviceBackground: "community_service",
    pets: "cat",
    alignmentLabel: "Strong Alignment",
    sharedStrengths: [
          "Relationship goals align",
          "Faith importance aligns",
          "Desire for children aligns",
          "Service values align",
          "Lifestyle habits appear compatible"
    ],
    importantFactors: [],
    importantFactorsSummary: null,
    noFactorsCopy: "No major alignment concerns surfaced from the information currently available.",
    characterSignalIds: ["kind_conversation","clear_intentions","genuine_and_present","great_listener"] as CharacterSignalId[],
    isMutualConnection: false,
    photoFiles: ["justin-reed-1.png"],
  },
  {
    id: "seed-nathan-brooks",
    gender: "man",
    firstName: "Nathan",
    lastName: "Brooks",
    age: 39,
    locationCity: "Castle Rock",
    locationRegion: "Colorado",
    aboutPreview: "Measured speaker. I think before I answer, which some people mistake for distance. It is usually care.",
    moreAbout: "Corporate counsel who left active-duty Army years ago. Has kids and is open to more depending on the relationship. Faith is somewhat important. Non-smoker; drinking incomplete. Relocation unanswered.",
    career: "Corporate counsel",
    education: "graduate_professional",
    thingsIEnjoy: ["Running","History books","Kids activities","Grilling"],
    relationshipGoal: "serious_relationship",
    faithImportance: "somewhat_important",
    faithDescription: null,
    children: "open",
    hasChildren: "yes",
    openToPartnerWithChildren: "yes",
    smoking: "never",
    drinking: null,
    relocation: null,
    serviceBackground: "military",
    pets: "dog",
    alignmentLabel: "More to Discover",
    sharedStrengths: [
          "Both want commitment",
          "Blended-family openness aligns",
          "Communication appears careful and respectful"
    ],
    importantFactors: [
      {
        id: "nathan-brooks-military",
        title: "Military Service",
        severity: "informational",
        summary: "Military background may shape communication and structure",
        explanation: "Nathan’s service background can influence pacing and expectations. This is informational unless values conflict.",
      },
      {
        id: "nathan-brooks-drinking",
        title: "Drinking",
        severity: "informational",
        summary: "Drinking preferences are incomplete",
        explanation: "Missing drinking answers are not treated as negative — they invite clarification.",
      },
      {
        id: "nathan-brooks-relocation",
        title: "Relocation",
        severity: "worth_discussing",
        summary: "Relocation information is incomplete",
        explanation: "Forge does not yet have complete relocation answers from Nathan. Clarify if a shared future requires flexibility.",
      },
      {
        id: "nathan-brooks-faith",
        title: "Faith",
        severity: "worth_discussing",
        summary: "Faith importance differs somewhat",
        explanation: "Differences in how central faith is may matter as the relationship deepens.",
      }
    ],
    importantFactorsSummary: "Faith and relocation need clarification · more to learn",
    characterSignalIds: ["respectful_communicator","great_listener","handled_mismatch_respectfully"] as CharacterSignalId[],
    isMutualConnection: true,
    photoFiles: ["nathan-brooks-1.png","nathan-brooks-2.png","nathan-brooks-3.png"],
  },
  {
    id: "seed-adam-porter",
    gender: "man",
    firstName: "Adam",
    lastName: "Porter",
    age: 35,
    locationCity: "Aurora",
    locationRegion: "Colorado",
    aboutPreview: "Friendly and unfinished — still completing my Forge profile while looking for a serious connection.",
    moreAbout: "Warehouse operations supervisor. I joined Forge recently and have only completed relationship goal and location so far. More preference answers are coming.",
    career: "Warehouse operations supervisor",
    education: null,
    thingsIEnjoy: [],
    relationshipGoal: "serious_relationship",
    faithImportance: null,
    faithDescription: null,
    children: null,
    hasChildren: null,
    openToPartnerWithChildren: null,
    smoking: "never",
    drinking: null,
    relocation: null,
    serviceBackground: null,
    pets: null,
    alignmentLabel: "Not Enough Information",
    sharedStrengths: [
          "Interested in a serious relationship",
          "Lives nearby",
          "Seems communication-oriented"
    ],
    whySurfacedCopy: "Adam’s stated relationship intentions and Aurora location may be relevant, but Forge needs more information before offering a responsible Relationship Alignment assessment.",
    importantFactors: [],
    importantFactorsSummary: null,
    incompleteAssessmentCopy: "Forge does not have enough information to offer a responsible Relationship Alignment assessment yet.",
    characterSignalIds: [] as CharacterSignalId[],
    isMutualConnection: false,
    photoFiles: ["adam-porter-1.png"],
  },
  {
    id: "seed-eric-lawson",
    gender: "man",
    firstName: "Eric",
    lastName: "Lawson",
    age: 44,
    locationCity: "Colorado Springs",
    locationRegion: "Colorado",
    aboutPreview: "Quiet confidence. I fly fish at dawn, teach shop class, and want a partner who does not need constant performance.",
    moreAbout: "High school shop teacher and former Marine. Two kids mostly grown. Open to partnership without more children. Faith is important. Non-smoker, occasional drinker. Prefer staying in Colorado Springs.",
    career: "High school shop teacher",
    education: "bachelors",
    thingsIEnjoy: ["Fly fishing","Woodworking","Teaching","Classic cars"],
    relationshipGoal: "serious_relationship",
    faithImportance: "important",
    faithDescription: "Faith and military service both shape integrity expectations.",
    children: "no",
    hasChildren: "yes",
    openToPartnerWithChildren: "yes",
    smoking: "never",
    drinking: "occasionally",
    relocation: "not_open",
    serviceBackground: "military",
    pets: "dog",
    alignmentLabel: "Promising Alignment",
    sharedStrengths: [
          "Commitment intentions align",
          "Faith importance aligns",
          "Comfort with established family life aligns",
          "Service background is valued"
    ],
    importantFactors: [
      {
        id: "eric-lawson-relocation",
        title: "Relocation",
        severity: "worth_discussing",
        summary: "Relocation preferences may differ",
        explanation: "Eric prefers remaining in Colorado Springs for work and community. Clarify geographic expectations if the relationship becomes serious.",
      },
      {
        id: "eric-lawson-military",
        title: "Military Service",
        severity: "informational",
        summary: "Military background may shape household rhythms",
        explanation: "Structure and directness from Eric’s Marine background can be a strength — still worth understanding how it shows up day to day.",
      }
    ],
    importantFactorsSummary: "Relocation preferences deserve conversation",
    characterSignalIds: ["respectful_in_person","consistent_follow_through","clear_intentions"] as CharacterSignalId[],
    isMutualConnection: false,
    photoFiles: ["eric-lawson-1.png"],
  },
  {
    id: "seed-steven-hart",
    gender: "man",
    firstName: "Steven",
    lastName: "Hart",
    age: 47,
    locationCity: "Cheyenne",
    locationRegion: "Wyoming",
    aboutPreview: "Blunt in a good way. I ranch on weekends, consult during the week, and do not pretend to be someone I am not.",
    moreAbout: "Agricultural consultant with adult kids. Does not want a parenting role again. Faith is somewhat important. Smokes cigars occasionally. Drinks socially. Open to relocating into Colorado for the right relationship.",
    career: "Agricultural consultant",
    education: "bachelors",
    thingsIEnjoy: ["Ranch work","Hunting","Country music","Cooking outdoors"],
    relationshipGoal: "serious_relationship",
    faithImportance: "somewhat_important",
    faithDescription: null,
    children: "no",
    hasChildren: "yes",
    openToPartnerWithChildren: "no",
    smoking: "occasionally",
    drinking: "socially",
    relocation: "open",
    serviceBackground: null,
    pets: "dog",
    alignmentLabel: "More to Discover",
    sharedStrengths: [
          "Both want a serious relationship",
          "Both prefer direct communication",
          "Geographic distance is workable with relocation openness"
    ],
    importantFactors: [
      {
        id: "steven-hart-children",
        title: "Children",
        severity: "potential_dealbreaker",
        summary: "Potential dealbreaker: Children preferences differ",
        explanation: "Steven does not want a parenting role. If a partner wants children or has young kids needing a co-parent, this may be a dealbreaker.",
        viewerAnswer: "Open to raising children within the relationship",
        partnerAnswer: "Does not want a parenting role",
        isPotentialDealbreaker: true,
      },
      {
        id: "steven-hart-smoking",
        title: "Smoking",
        severity: "worth_discussing",
        summary: "Smoking preferences conflict",
        explanation: "Occasional cigar smoking may conflict with a smoke-free preference.",
      },
      {
        id: "steven-hart-lifestyle",
        title: "Lifestyle",
        severity: "informational",
        summary: "Rural lifestyle rhythms may differ",
        explanation: "Weekend ranch work and rural routines may differ from city life. Worth discussing lifestyle fit early.",
      }
    ],
    importantFactorsSummary: "Potential dealbreaker: Children preferences differ",
    characterSignalIds: ["clear_intentions","respectful_communicator"] as CharacterSignalId[],
    isMutualConnection: false,
    photoFiles: ["steven-hart-1.png"],
  },
  {
    id: "seed-patrick-doyle",
    gender: "man",
    firstName: "Patrick",
    lastName: "Doyle",
    age: 36,
    locationCity: "Fort Collins",
    locationRegion: "Colorado",
    aboutPreview: "Irish stubbornness softened by kindness. I coach Special Olympics soccer and want a partner who notices the quiet good people do.",
    moreAbout: "Physical therapist specializing in sports rehab. No kids yet; wants a family. Faith is important. Non-smoker, rare drinker. Open to relocating within Colorado or nearby states.",
    career: "Physical therapist",
    education: "graduate_professional",
    thingsIEnjoy: ["Special Olympics coaching","Soccer","Hiking","Coffee shops"],
    relationshipGoal: "serious_relationship",
    faithImportance: "important",
    faithDescription: "Faith fuels service and relationship intentions.",
    children: "yes",
    hasChildren: "no",
    openToPartnerWithChildren: "yes",
    smoking: "never",
    drinking: "rarely",
    relocation: "open",
    serviceBackground: "healthcare",
    pets: "dog",
    alignmentLabel: "Strong Alignment",
    sharedStrengths: [
          "Relationship goals align",
          "Faith importance aligns",
          "Desire for children aligns",
          "Healthcare and service values align",
          "Lifestyle habits appear compatible"
    ],
    importantFactors: [],
    importantFactorsSummary: null,
    noFactorsCopy: "No major alignment concerns surfaced from the information currently available.",
    characterSignalIds: ["genuine_and_present","kind_conversation","consistent_follow_through","great_listener"] as CharacterSignalId[],
    isMutualConnection: false,
    photoFiles: ["patrick-doyle-1.png"],
  },
  {
    id: "seed-gregory-lane",
    gender: "man",
    firstName: "Gregory",
    lastName: "Lane",
    age: 46,
    locationCity: "Littleton",
    locationRegion: "Colorado",
    aboutPreview: "Patient and dry-witted. I garden like it is a second career and prefer dinners that last longer than the recipe says.",
    moreAbout: "Architect with one college-age son. Open to a serious relationship; not seeking more children. Faith is somewhat important. Non-smoker, occasional wine. Prefer remaining along the Front Range.",
    career: "Architect",
    education: "graduate_professional",
    thingsIEnjoy: ["Gardening","Design museums","Cooking","Jazz"],
    relationshipGoal: "serious_relationship",
    faithImportance: "somewhat_important",
    faithDescription: null,
    children: "no",
    hasChildren: "yes",
    openToPartnerWithChildren: "yes",
    smoking: "never",
    drinking: "occasionally",
    relocation: "not_open",
    serviceBackground: null,
    pets: "cat",
    alignmentLabel: "Promising Alignment",
    sharedStrengths: [
          "Commitment intentions align",
          "Comfort with established family life aligns",
          "Lifestyle habits largely compatible",
          "Communication appears thoughtful"
    ],
    importantFactors: [
      {
        id: "gregory-lane-faith",
        title: "Faith",
        severity: "worth_discussing",
        summary: "Faith importance differs somewhat",
        explanation: "Gregory treats faith as meaningful but not central. Discuss how shared values would look in practice.",
      },
      {
        id: "gregory-lane-relocation",
        title: "Relocation",
        severity: "worth_discussing",
        summary: "Relocation preferences may differ",
        explanation: "Gregory prefers remaining along the Front Range. Clarify geographic expectations early.",
      }
    ],
    importantFactorsSummary: "Faith and relocation deserve conversation",
    characterSignalIds: ["great_listener","respectful_communicator","respectful_in_person"] as CharacterSignalId[],
    isMutualConnection: true,
    photoFiles: ["gregory-lane-1.png","gregory-lane-2.png","gregory-lane-3.png"],
  },
  {
    id: "seed-jonathan-west",
    gender: "man",
    firstName: "Jonathan",
    lastName: "West",
    age: 32,
    locationCity: "Albuquerque",
    locationRegion: "New Mexico",
    aboutPreview: "Creative and restless in a good way. I write songs no one asked for and show up early to help load gear for friends’ bands.",
    moreAbout: "Music teacher and weekend producer. Unsure about kids. Faith is not important. Social drinker. Prefer staying in New Mexico near family, though Colorado is discussable for the right person.",
    career: "Music teacher",
    education: "bachelors",
    thingsIEnjoy: ["Songwriting","Live music","Hiking","Photography"],
    relationshipGoal: "serious_relationship",
    faithImportance: "not_important",
    faithDescription: null,
    children: "unsure",
    hasChildren: "no",
    openToPartnerWithChildren: "yes",
    smoking: "never",
    drinking: "socially",
    relocation: "possibly",
    serviceBackground: "education",
    pets: "dog",
    alignmentLabel: "More to Discover",
    sharedStrengths: [
          "Both want a meaningful relationship",
          "Creative and community values appear compatible",
          "Communication style seems open"
    ],
    importantFactors: [
      {
        id: "jonathan-west-faith",
        title: "Faith",
        severity: "worth_discussing",
        summary: "Faith importance differs",
        explanation: "Jonathan does not center faith in daily life. This difference may matter depending on practice within a relationship.",
        viewerAnswer: "Faith is an important relationship value",
        partnerAnswer: "Faith is not important",
      },
      {
        id: "jonathan-west-children",
        title: "Children",
        severity: "informational",
        summary: "Children intentions are still forming",
        explanation: "Uncertainty around children invites conversation rather than a negative judgment.",
      },
      {
        id: "jonathan-west-relocation",
        title: "Relocation",
        severity: "worth_discussing",
        summary: "Relocation preferences may need compromise",
        explanation: "Jonathan prefers New Mexico but is open to discussing Colorado. Shared geography deserves early clarity.",
      }
    ],
    importantFactorsSummary: "Faith, children, and relocation need clarification",
    characterSignalIds: ["kind_conversation","genuine_and_present"] as CharacterSignalId[],
    isMutualConnection: false,
    photoFiles: ["jonathan-west-1.png"],
  },
  {
    id: "seed-daniel-cruz",
    gender: "man",
    firstName: "Daniel",
    lastName: "Cruz",
    age: 31,
    locationCity: "Denver",
    locationRegion: "Colorado",
    aboutPreview: "New profile, clear intention: looking for something serious once my answers are complete.",
    moreAbout: "Restaurant manager who works late nights and just started on Forge. Most preference fields are still empty. I know I want commitment and respect.",
    career: "Restaurant manager",
    education: null,
    thingsIEnjoy: ["Cooking"],
    relationshipGoal: "serious_relationship",
    faithImportance: null,
    faithDescription: null,
    children: null,
    hasChildren: null,
    openToPartnerWithChildren: null,
    smoking: null,
    drinking: null,
    relocation: null,
    serviceBackground: null,
    pets: null,
    alignmentLabel: "Not Enough Information",
    sharedStrengths: [
          "Interested in a serious relationship",
          "Denver-based",
          "Values respect"
    ],
    whySurfacedCopy: "Daniel’s relationship goal and Denver location may be relevant, but Forge needs more completed preference answers before offering a responsible Relationship Alignment assessment.",
    importantFactors: [],
    importantFactorsSummary: null,
    incompleteAssessmentCopy: "Forge does not have enough information to offer a responsible Relationship Alignment assessment yet.",
    characterSignalIds: [] as CharacterSignalId[],
    isMutualConnection: false,
    photoFiles: ["daniel-cruz-1.png"],
  }
];

export function getSeedProfiles(): readonly SeedProfile[] {
  return SEED_PROFILES;
}

export function getSeedProfileById(id: string): SeedProfile | undefined {
  return SEED_PROFILES.find((profile) => profile.id === id);
}

/** All seed profiles are eligible for Discovery. */
export function getSeedDiscoveryProfiles(): readonly SeedProfile[] {
  return SEED_PROFILES;
}

export function getSeedMutualConnectionProfiles(): readonly SeedProfile[] {
  return SEED_PROFILES.filter((profile) => profile.isMutualConnection);
}
